GET http://localhost:8081/upload-photo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YjViYTBhMC1kYTlhLTRlY2UtYjgwYS0wZWJmODFmNzc3OGUiLCJleHAiOjE3NDg5ODI2NzUsImlhdCI6MTc0ODg5NjI3NSwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiLCJhZG1pbiIsImFub255bW91cyJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJhZG1pbiIsIngtaGFzdXJhLXVzZXItaWQiOiI1YjViYTBhMC1kYTlhLTRlY2UtYjgwYS0wZWJmODFmNzc3OGUifX0.HkRryzziPjA2fT1oeAWv0omwQ0mxlEEelafv5MwkUc0